version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: trino_postgres
    environment:
      POSTGRES_USER: trino
      POSTGRES_PASSWORD: trino
      POSTGRES_DB: trino
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  trino:
    image: trinodb/trino:latest
    container_name: trino_dev
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./trino-config/catalog:/etc/trino/catalog
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx6G

volumes:
  pg_data:
