[project]
name = "jaffle-shop-colibri"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-colibri==0.2.2",
    "dbt-core==1.8",
    "dbt-snowflake",
]
