name: dbt Colibri Example
on:
  push:
    branches:
      - "*"
jobs:
  deploy_colibri:
    name: Deploy Colibri Example
    runs-on: macos-latest

    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"
      - name: Install uv
        run: python3 -m pip install uv
      - name: Install deps
        run: uv pip install -r requirements.txt --system
      - name: Initialize dbt
        run: echo "dbt deps"
      - name: Initialize dbt
        run: echo "dbt compile && dbt test"
      - name: Run Colibri
        run: colibri generate
      # Deploy to GitHub Pages (or other destination)
      - name: Deploy Colibri HTML
        run: |
          # Ensure that the index.html is generated in the output dir
          if [ -f dist/index.html ]; then
            echo "Deploying HTML to GitHub Pages..."
            
            # If using GitHub Pages, copy the HTML file to the docs folder or desired directory
            cp dist/index_inlined.html ./docs/index.html

            # Configure Git for committing changes
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            
            # Commit the changes and push to the gh-pages branch
            git add docs/index.html
            git commit -m "Deploy Colibri HTML"
            git push origin gh-pages
          else
            echo "Error: index.html not found in colibri_output!"
            exit 1
          fi
